### ISSUE TITLE
Add input constraints where necessary (user profile: description, preference; etc.) [4h]

### ISSUE THREAD

**Issue by SFulpius** [SwengGolfTeam/Sweng_Golf#100]
Here are all the activities that have an EditText. For each EditText field there is a minimum and maximum number of characters.

* CreateOfferActivity
  * title : min 1, max 50
  * description : min 10, max 1000
* EditProfileActivity
  * username : min 1, max 25
  * infos : min 0, max 200
  * preferences : min 0, max 100
* CreateUserActivity
  * username : same as in EditProfileActivity
  * email (already handled by a cutom regex)
* ShowOfferActivity
  * response to an offer : min 4, max 200

What do you think of these limits ? If you find that some limits are too low/high or if I forgot some fields, feel free to leave a comment.

**Comment by udamiano** [comment]
Maybe the username should be longer than 1 char ? Three seems good to me. And maybe the description of an offer should be at least one sentence, something like 8 ?

**Comment by ElsaWeb** [comment]
Yeah, it seems good, apart maybe from the response to an offer; 1000 characters seems a bit much to me, I'm pretty sure everything could be said in 100 (200 maybe) characters, and if needed they can contact each other to further discuss the matter. Also, is there a particular reason why you put 200 for infos, and only 100 for preferences? These twos fields seem similar to me, and I was thinking 100 was enough for both.

**Comment by udamiano** [comment]
You might want to tell what is your job, your activities and where you live in your description. Whereas in the preferences you might at most tell a specific service or two up to three things you're looking for. Does that answers your question @ElsaWeb ?

**Comment by SFulpius** [comment]
I updated it according to your comments. As Ugo said, you have probably more to say about you that about your preferences.
