### ISSUE TITLE
Figure out why DeleteOfferTest fails only sometimes on Travis and fix it [3h]

### ISSUE THREAD

**Issue by robinmamie** [SwengGolfTeam/Sweng_Golf#115]

**Comment by dingepfl** [comment]
Version of the file that was causing problems: [`DeleteOfferTest.java`](https://github.com/SwengGolfTeam/Sweng_Golf/blob/3983419a3315271786f6b65b7808a73765530466/app/src/androidTest/java/ch/epfl/sweng/swenggolf/DeleteOfferTest.java)

More specifically the `cancelDialog()` Test that was sometime failing on Travis only (not in local) with the following message:

```
ch.epfl.sweng.swenggolf.DeleteOfferTest > cancelDialog[test(AVD) - 5.1.1] [31mFAILED [0m
	android.support.test.espresso.PerformException: Error performing 'load adapter data' on view 'an instance of android.widget.AdapterView'.

	at android.support.test.espresso.PerformException$Builder.build(PerformException.java:82)
```
