### ISSUE TITLE
As a user, I want to see points and badges on user profile [5h]

### ISSUE THREAD

**Issue by ElsaWeb** [SwengGolfTeam/Sweng_Golf#125]

**Comment by dingepfl** [comment]
Done in PR https://github.com/SwengGolfTeam/Sweng_Golf/pull/134

**Comment by dingepfl** [comment]
The badges will be upgraded to higher quality ones in the upcoming days

**Comment by dingepfl** [comment]
High quality portraits added in PR https://github.com/SwengGolfTeam/Sweng_Golf/pull/140
