### ISSUE TITLE
As a user, I want to be able to gain points.[10h]

### ISSUE THREAD

**Issue by ElsaWeb** [SwengGolfTeam/Sweng_Golf#127]

**Comment by udamiano** [comment]
Hi, we need to decide what points are given for an action, I propose the following : 
* Create an offer +1 : 
 * with a picture +1
 * with a location +1
* Be selected as a favorite in an offer +10
Just as we discussed, the options you add to the offer increase the points you win.
I think that helping someone is more difficult and demanding so I put 10 points for it.
Are the points too much or not enough ? I was thinking that we might also win points when being followed, like "this person is great ! I follow him !" And when you stop following the person points are reverted. If we had this option I was thinking about 2 points.

**Comment by ElsaWeb** [comment]
Great idea! I think it's perfect like this :+1:

**Comment by ejolles** [comment]
https://github.com/SwengGolfTeam/Sweng_Golf/blob/d74f9ab0045cb4869aa48242478f35b2491eec9e/app/src/main/java/ch/epfl/sweng/swenggolf/profile/PointType.java#L6-L10

**Comment by ejolles** [comment]
This is the place where we can modify the points you can change the value as you want but if you do it it must be in this enum!

**Comment by udamiano** [comment]
Thanks @ejolles, what do you think of the points repartitions ?

**Comment by robinmamie** [comment]
I agree with the value of the points. Nevertheless, I would be for putting barriers to avoid any excess.

Either we can limit the number of offers we can create in a certain timespan, or we could limit the number of points we can gain in a given day. What do you think?

**Comment by udamiano** [comment]
Yes it would be a nice idea. And how would you manage the time ? By counting how many offers are done on a given day and then resetting every day the whole database at midnight ?

**Comment by dingepfl** [comment]
I think that barriers are a good idea as well but it isn't needed for the first implementation as mentioned by @ejolles. So we can think about it and reconsider/decide later on how to implement it
