### ISSUE TITLE
As a user, I want that the app refreshes all data automatically.[10h]

### ISSUE THREAD

**Issue by robinmamie** [SwengGolfTeam/Sweng_Golf#167]

**Comment by udamiano** [comment]
Hi, can you tell me which part of the app should refresh automatically ? The answers in ShowOffer, the points in the profile maybe ? Any other ideas ? For the list of offers I was thinking about putting a refresh button or something like that.

**Comment by SFulpius** [comment]
The most important are the answers in the offer and in the future the messages after an offer is closed. We can always add it to other places later.

**Comment by ElsaWeb** [comment]
I agree with that too :+1:

**Comment by ejolles** [comment]
Yes the answers are the most important thing to refresh now, but I think in the future all the recycler views should be refreshed.
