### ISSUE TITLE
>= 80% test coverage

### ISSUE THREAD

**Issue by dingepfl** [SwengGolfTeam/Sweng_Golf#45]
We need to improve the coverage of these files (not grade `A` in [overview](https://codeclimate.com/github/SwengGolfTeam/Sweng_Golf/code?sort=test_coverage), tick the box when code coverage is ` >=90%`):

- [ ] [SignInActivity.java](https://codeclimate.com/github/SwengGolfTeam/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/database/SignInActivity.java) `35%` -> `X%`
- --------------------------------------------------------------- D ( 60% - 69% )
- [ ] [ViewUserFiller.java](https://codeclimate.com/github/SwengGolfTeam/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/tools/ViewUserFiller.java) `66%` -> `X%`
- --------------------------------------------------------------- C ( 70% - 79% )
- [ ] [StorageConnection.java](https://codeclimate.com/github/SwengGolfTeam/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/database/StorageConnection.java) `78%` -> `X%`
- --------------------------------------------------------------- B ( 80% - 89% )
- [x] [FireDatabase.java](https://codeclimate.com/github/SwengGolfTeam/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java) `0%` -> `80%`
- [x] [WaitingActivity.java](https://codeclimate.com/github/SwengGolfTeam/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/database/WaitingActivity.java)  `0%` -> `85%`
- --------------------------------------------------------------- A ( 90% - 100% )
- [x] [Database.java](https://codeclimate.com/github/SwengGolfTeam/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java) `70%` -> `90%`
- [x] [ListPreferenceAdapter.java](https://codeclimate.com/github/SwengGolfTeam/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/preference/ListPreferenceAdapter.java) `63%` -> `92%`
- [x] [CreateUserActivity.java](https://codeclimate.com/github/SwengGolfTeam/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/database/CreateUserActivity.java) `88%` -> `96%`
- [x] [EditProfileActivity.java](https://codeclimate.com/github/SwengGolfTeam/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/profile/EditProfileActivity.java) `77%` -> `100%`
- [x] [FakeUserDatabase.java](https://codeclimate.com/github/udamiano/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeUserDatabase.java) `0%` -> `deleted`
- [x] [DatabaseConnection.java](https://codeclimate.com/github/udamiano/Sweng_Golf/app/src/main/java/ch/epfl/sweng/swenggolf/database/DatabaseConnection.java) `62%` -> `deleted`

**Comment by dingepfl** [comment]
### Example.java
Improved to 85% in commit https://github.com/SwengGolfTeam/Sweng_Golf/commit/78ee1d9340ed49ea8c5aefd0c28e0791be176e2a

------
Copy-paste template to use:
`### Example.java
Improved to 85% in commit https://github.com/SwengGolfTeam/Sweng_Golf/commit/78ee1d9340ed49ea8c5aefd0c28e0791be176e2a`

**Comment by robinmamie** [comment]
### FakeUserDatabase.java

Removed in commit https://github.com/SwengGolfTeam/Sweng_Golf/commit/535a8bb6c759a952e434f8c94e37126009920527

**Comment by SFulpius** [comment]
Just a note for FireDatabase : the class is hard to test as it use FirebaseDatabase. We could test it using dependency injection and mocking FirebaseDatabase with Mockito, but this will take a lot of time. If you really want to test it, do it last.

**Comment by ejolles** [comment]
> Just a note for **FireDatabase.java** : the class is hard to test as it use FirebaseDatabase. We could test it using dependency injection and mocking FirebaseDatabase with Mockito, but this will take a lot of time. If you really want to test it, do it last.

Cannot we use the Database we mocked earlier to test this class?

**Comment by SFulpius** [comment]
> Cannot we use the Database we mocked earlier to test this class?
You mean FakeDatabase ? Or the currently removed class FakeFirebaseDatabase which used Mockito ?

**Comment by dingepfl** [comment]
### DatabaseConnection.java
`Deleted` in commit 22e996e4269f4bb6a3125359a67f52bd230bb657

**Comment by dingepfl** [comment]
### Database.java
Improved to 90% in commit f61124e8239702868c9df85deb8866f177701a8e

**Comment by dingepfl** [comment]
### ListPreferenceAdapter.java
Improved to 92% (refactoring of the file) in commit f86bf3c746736df66c52aeb5403aab620808d98c

**Comment by ejolles** [comment]
### EditProfileActivity.java
Improved to 100% in commit 5aa5c698178d9a2e9a2cf95c9e6f734ac5c34520

**Comment by robinmamie** [comment]
### CreateUserActivity.java

Improved to 96% in commit 7b54c2cd9adc3bd4c230f1079d8e64916edeaf7f

**Comment by robinmamie** [comment]
### FireDatabase.java

Improved to 48% in commit 1244d0640f48fd8a227888b73101fa9d8e5b2c79
