### ISSUE TITLE
Fix bug regarding double offer in database after creation

### ISSUE THREAD

**Issue by robinmamie** [SwengGolfTeam/Sweng_Golf#58]

**Comment by robinmamie** [comment]
The bug is caused by the button not locking during the creation of the offer. Thus, impatient users (poke @SFulpius) can create the same offer several times.

**Comment by dingepfl** [comment]
Some possible solutions might be:
- Freeze/remove the button once pressed
- Show a visual loading queue so the user knows that its button press was registered
- move to another activity once pressed

**Comment by robinmamie** [comment]
The PR #67 fixes this bug.
